[profile.default]
name = 'contracts-template'
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
evm_version = "shanghai"
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.mainnet]
libraries = [
    "src/strategy/StructuredLinkedList.sol:StructuredLinkedList:0x6C566a67b34CFed9821FC7433750A1391fa97989",
    "src/strategy/WithdrawalQueue.sol:WithdrawalQueue:0xC754773B0e8CaFbD17e978be3c31ef34869ba733",
    "src/vault/libs/AutoPoolToken.sol:AutoPoolToken:0x9a64511219Fd5aE18ED06088dded100a3c579b26",
    "src/vault/libs/LMPDebt.sol:LMPDebt:0x6e4FD2077df6754EC257C13D7A4dEbbe717f9d48",
    "src/vault/libs/LMPDestinations.sol:LMPDestinations:0x5B6EAaC27CDeba310A335aFeC9d18f9b3137EFA5",
    "src/vault/libs/AutoPool4626.sol:AutoPool4626:0xDf768df195eDE3172E971Cfc1968f703BF325109",
    "src/vault/libs/AutoPoolFees.sol:AutoPoolFees:0x447536DF798693404686266ba4c8800aDE8372A3",
    "src/destinations/adapters/staking/ConvexAdapter.sol:ConvexStaking:0x6c2f91978004B0A769c622dfe352EdF331044d49",
    "src/destinations/adapters/rewards/ConvexRewardsAdapter.sol:ConvexRewards:0x08F295fD04B52Ab6a7f8A86bC9A0A1c0EA8aDE01",
    "src/destinations/adapters/CurveV2FactoryCryptoAdapter.sol:CurveV2FactoryCryptoAdapter:0xe46E7634d6e0BC954407078818fF62eDfF414184",
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
single_line_statement_blocks = "preserve" # can force either way
exclude = ['lib/']

[fuzz]

# env FOUNDRY_FUZZ_RUNS=
runs = 50
# env FOUNDRY_FUZZ_MAX_TEST_REJECTS=2147483647
# max_test_rejects = 2147483647
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
